image: node:lts

cache:
  paths:
    - node_modules/

stages:
  - test

test_integration:
  stage: test
  script:
    - npm install
    - npm test
  services:
    - name: arangodb:latest
      alias: arangodb
  tags:
    - docker
  variables:
    TEST_ARANGO_URL: "http://arangodb:8529"
  coverage: '^Statements\s*:\s*([^%]+)'
