image: node:lts

cache:
  paths:
    - node_modules/

stages:
  - test

test_integration:
  stage: test
  script:
    - npm install
    - npm test
  # https://github.com/biggora/caminte/blob/master/.gitlab-ci.yml
  services:
    - name: arangodb:latest
      alias: arangodb
      command: [ "export ARANGO_NO_AUTH=1" ]
  tags:
    - docker
  variables:
    TEST_ARANGO_URL: "http://arangodb:8529"
    ARANGO_NO_AUTH: "1"
  coverage: /^Statements\s*:\s*([^%]+)/
